### ISSUE TITLE
模型训练与验证问题

### ISSUE THREAD

**Issue by wwwqql** [Anonymous123xx/RLRep#4]
RLRep为智能合约开发者自动提供智能合约修复建议。希望可以复现该工具。在复现过程中遇到以下几个问题，希望您可以解答：
1. 运行该命令python main.py multistep_RLRep dataset_vul/newALLBUGS，出现：
line 1:8 mismatched input '(' expecting 'constant'
line 1:16 mismatched input '!=' expecting 'constant'
line 1:27 mismatched input '(' expecting 'constant'
line 1:41 mismatched input '>' expecting 'constant'
line 1:58 mismatched input '>' expecting 'constant'
line 1:68 mismatched input ':=' expecting 'constant'
line 1:77 mismatched input '(' expecting 'constant'
line 1:30 extraneous input '<' expecting {'~', 'from', '{', '}', '(', 'error', 'for', 'function', '[', 'address', 'mapping', 'calldata', 'if', 'try', 'while', 'unchecked', 'asse
mbly', 'do', 'return', 'throw', 'emit', 'revert', 'var', 'bool', 'string', 'byte', '++', '--', 'new', '+', '-', 'after', 'delete', '!', 'callback', Int, Uint, Byte, Fixed, Ufixed, BooleanLiteral, DecimalNumber, HexNumber, HexLiteralFragment, 'break', 'continue', 'leave', 'payable', 'type', 'constructor', 'receive', Identifier, StringLiteralFragment}   
line 1:36 extraneous input 'if' expecting {'~', 'from', '(', 'error', '[', 'address', 'calldata', 'revert', 'var', 'bool', 'string', 'byte', '++', '--', 'new', '+', '-', 'after'
, 'delete', '!', 'callback', Int, Uint, Byte, Fixed, Ufixed, BooleanLiteral, DecimalNumber, HexNumber, HexLiteralFragment, 'leave', 'payable', 'type', 'constructor', 'receive', Identifier, StringLiteralFragment}
line 1:65 missing ';' at '{'
line 1:67 extraneous input '<' expecting {'~', 'from', '{', '}', '(', 'error', 'for', 'function', '[', 'address', 'mapping', 'calldata', 'if', 'try', 'while', 'unchecked', 'asse
mbly', 'do', 'return', 'throw', 'emit', 'revert', 'var', 'bool', 'string', 'byte', '++', '--', 'new', '+', '-', 'after', 'delete', '!', 'callback', Int, Uint, Byte, Fixed, Ufixed, BooleanLiteral, DecimalNumber, HexNumber, HexLiteralFragment, 'break', 'continue', 'leave', 'payable', 'type', 'constructor', 'receive', Identifier, StringLiteralFragment}   
line 1:73 mismatched input 'return' expecting {'~', 'from', '(', 'error', '[', 'address', 'calldata', 'revert', 'var', 'bool', 'string', 'byte', '++', '--', 'new', '+', '-', 'af
ter', 'delete', '!', 'callback', Int, Uint, Byte, Fixed, Ufixed, BooleanLiteral, DecimalNumber, HexNumber, HexLiteralFragment, 'leave', 'payable', 'type', 'constructor', 'receive', Identifier, StringLiteralFragment}
line 2:0 mismatched input '<EOF>' expecting '}'
Traceback (most recent call last):
  File "D:\桌面\RLRep11\RLRep\main.py", line 72, in <module>
    loss = model(batch[:-1], True, batch[-1])
  File "D:\桌面\RLRep11\RLRep\.venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\桌面\RLRep11\RLRep\.venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\桌面\RLRep11\RLRep\multistep_RLRep.py", line 388, in forward
    return self.train_on_batch(inputs, contracts)
  File "D:\桌面\RLRep11\RLRep\multistep_RLRep.py", line 410, in train_on_batch
    res = choose_action(contracts[i], preds[i], True)
  File "D:\桌面\RLRep11\RLRep\utils2.py", line 325, in choose_action
    lines = sf.readlines()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa3 in position 1176: illegal multibyte sequence
这种是报错还是在训练模型。

2.用法中步骤二中
第一个输入：threelines-tokenseq/
第二个输入：ast
预训练数据： 和pretrain/pretrain_label/
验证数据：validation/
这几个命令是直接通过python main.py multistep_RLRep dataset_vul/newALLBUGS使用吗，还是用python main.py multistep_RLRep dataset_vul/newALLBUGS/ast这种

3.最后修复建议是保存在dataset_vul/newALLBUGS/validation/result/路径下，还是在RLRep\dataset_vul\newALLBUGS\repair_contract路径下只有修复完的代码。

上面问题就是我在复现过程中遇到的问题，希望您能解答我的这些疑惑。我自己基础较差有些看不明白您在githup上自述文件中的步骤，如果有更加完整的操作手册或者步骤、合约成功修复的案例能不能发到我的邮箱2932026137@qq.com

**Comment by wwwqql** [comment]
我把遇到的主要问题放在word中并添加了相关图片，请您帮忙看看我应该如何避免这些问题。谢谢
[培训验证问题.docx](https://github.com/user-attachments/files/16138523/default.docx)

**Comment by Anonymous123xx** [comment]
Your system may be using gbk decoding by default, try to open it in utf-8 encoding.

**Comment by wwwqql** [comment]
非常感谢您能够帮我解决问题。
0x02f63293d2028a6de37f1d9545e66246a0a45911.sol这个文件我在Notepad++中打开默认是使用utf-8编码的。在PyCharm中打开更改后。我把dataset_vul\newALLBUGS\repair_contract文件夹中合约删除，重新调用命令 python main.py multistep_RLRep dataset_vul/newALLBUGS生成。也还是没有成功修复。
![image](https://github.com/Anonymous123xx/RLRep/assets/174608158/84a74cae-d676-411e-9b4b-c37af7cc449a)
![image](https://github.com/Anonymous123xx/RLRep/assets/174608158/822dc6f2-8665-4171-b94f-2e73ef917b2d)

**Comment by Henrykwokkk** [comment]
Set the encoding type in Pycharm, or change the `with open` code to make it open file with utf-8

**Comment by Anonymous123xx** [comment]
Set the encoding type in Pyhcarm or change `with open` code to make it open file by using utf-8.

**Comment by wwwqql** [comment]
改为utf-8，文件还是没有修复。麻烦你再帮忙看看，谢谢。
![image](https://github.com/Anonymous123xx/RLRep/assets/174608158/0a5eaa65-87e2-4148-b5d6-1561f1c0f5ac)
![image](https://github.com/Anonymous123xx/RLRep/assets/174608158/45184ee7-b7c4-46ca-9357-7523271ef57d)

**Comment by Henrykwokkk** [comment]
Modify `with open` code, please

**Comment by Anonymous123xx** [comment]
Modify `with open` code please

**Comment by wwwqql** [comment]
抱歉再次麻烦您，我重新按照步骤部署RlRep项目，但在为tree.py添加方法时又遇到了问题，我把问题描述与运行命令截图放到word文档中，请您帮忙看一下我是哪里有问题。感谢您一直能够回复并帮助我解决问题。
[Uploading 培训验证问题.docx…]()

**Comment by wwwqql** [comment]
[问题.docx](https://github.com/user-attachments/files/16155377/default.docx)
